### ISSUE TITLE
memory and cpu abnormal raise when use complex relations

### ISSUE THREAD

**Issue by Esp9527** [SanderMertens/flecs#1079]
**Describe the bug**
flecs v3.2.9

memory and cpu abnormal raise when use complex relations

**To Reproduce**
`

    #include <flecs.h>
    #include <vector>
    #include <iostream>
    #include <map>
    
    struct Player {
        int id;
    };
    
    struct Monster {
        double x = 0, y = 0;
    };
    
    struct Attack {
        double x = 0, y = 0;
    };
    
    struct Cast{};
    struct CastOf{};
    struct Damage{};
    struct Target{};
    struct CallOf{};
    struct Root{
        int tick;
    };
    struct Life{
        int tick;
    };
    
    int main(int, char *[]) {
        flecs::world world;
        world.component<Player>();
        world.component<Monster>();
        world.component<Attack>();
        world.component<Damage>();
        std::vector<flecs::entity> players, monsters, attacks;
    
        for(auto i = 0; i < 1000; ++i){
            auto player = world.entity().set<Player>({i});
            players.push_back(player);
            auto monster = world.entity().set<Monster>({0, 0});
            monsters.push_back(monster);
        }
    
        world.system<Root, Player>()
            .arg(1).singleton()
            .each([&monsters](flecs::entity e,  Root& r, Player& p){
                if((p.id % 20) != (r.tick % 20))
                    return;
    
                auto attack = e.world().entity();
                attack.set<Attack>({});
                attack.set<Life>({100});
                attack.add<CastOf>(e);
                attack.add<Target>(monsters[rand()%monsters.size()]);
                e.add<Cast>(attack);
            });
    
        world.system<Life>()
            .each([&monsters](flecs::entity e, Life& life){
                if(--life.tick <= 0)
                    e.destruct();
                else if(life.tick % 10 == 5){
                    e.add<Damage>(monsters[rand()%monsters.size()]);
                }
            });
    
        world.set<Root>({0});
        world.system<Root>()
            .each([](flecs::entity e, Root& root){
                root.tick += 1;
                if(root.tick % 20 != 0){
                    return;
                }
                auto a = e.world().filter_builder().term<Attack>().build();
                // there will print attack <= 5000
                std::cout << "tick : attack count" << a.count() << std::endl;
        });
        world.app().target_fps(20).run();
        return 0;
    }

`

**Expected behavior**
attack create 1000/s (life=5s)
attack will add follow relations

    attack.add<CastOf>(palyer);
    player.add<Cast>(attack);
    attack.add<Target>(monster);
    attack.add<Damage>(monster);

cpu will high, memory is Memory will continue to grow

**Additional context**
Add any other context about the problem here (operating system, hardware, ...).

**Comment by SanderMertens** [comment]
If you connect your application to the explorer, you'll see that this is due to a growth in the number of empty tables:

<img width="994" alt="Screenshot 2023-11-23 at 12 46 48 AM" src="https://github.com/SanderMertens/flecs/assets/9919222/783a14f6-4fc0-4aa8-bcbe-29efb3f73f1d">

The reason this is happening is because of these three lines:
```cpp
attack.add<CastOf>(e);
attack.add<Target>(monsters[rand()%monsters.size()]);
e.add<Damage>(monsters[rand()%monsters.size()]);
```

You have 1000 monsters, which means there are in total 1000 * 1000 * 1000 unique combinations of pairs. Unique combinations of components (and pairs) create tables in Flecs. So given enough time, your application will create 1 billion tables, which is a lot.

The memory growth can be solved by periodically cleaning up empty tables, which you can do by adding the following system to your application:

```cpp
    world.system()
      .interval(0.1)
      .no_readonly()
      .iter([](flecs::iter& it){
        ecs_delete_empty_tables(it.world(), 0, 1, 1, 0, 0);
      });
```

That doesn't solve the high CPU issue. Here there are a few things you can improve:

- The system that prints the attack count creates a filter each frame, which is a bit wasteful. Filters are also not as fast as queries, so to speed this up you can do this instead:

```cpp
    flecs::query<Attack> q = world.query<Attack>();

    world.set<Root>({0});
    world.system<Root>()
        .each([=](flecs::entity e, Root& root){
            // ...
            std::cout << "tick : attack count" << q.count() << std::endl;
    });

```

- The `CastOf`, `Target` and `Attack` relationships fragment your attack entities to the point where you only have a single attack entity per table. To fix this, you can turn these into union relationships ([docs on unions](https://www.flecs.dev/flecs/md_docs_Relationships.html#autotoc_md341)):
```cpp
    world.component<Attack>().add(flecs::Union);
    world.component<Damage>().add(flecs::Union);
    world.component<CastOf>().add(flecs::Union);
```

You could also consider making them regular components, like:
```cpp
struct Attack {
  flecs::entity entity;
};
```

**Comment by Esp9527** [comment]
Thank you very much!
