### ISSUE TITLE
Explorer hierarchy incomplete

### ISSUE THREAD

**Issue by maximegmd** [SanderMertens/flecs#1159]
**Describe the bug**
Using the explorer web app, the hierarchy does not go beyond 1 level.

**To Reproduce**
1. Create three entities such that c is a child of b and b is a child of a.
2. Open the explorer view and see that expanding a, shows b but expanding b does not show c.

**Comment by SanderMertens** [comment]
This seems to work:
<img width="745" alt="Screenshot 2024-02-25 at 10 07 35 AM" src="https://github.com/SanderMertens/flecs/assets/9919222/5626a4bc-1329-4949-8a10-dec0503c742b">

Can you share the code in which you create the three entities?

**Comment by SanderMertens** [comment]
Ah, this is because the entity name contains spaces, which causes problems with queries. What you can do instead is:
- replace the spaces in your entities with underscores
- call `e.set_doc_name("Name with spaces");`

**Comment by copygirl** [comment]
To be fair, from what I know, the issue only occurs when using expressions to build queries, similar to SQL injection. When you build queries using the query builder you can avoid the problem. Same I believe if you used the entity ID itself in the query expression. (Unsure why the explorer is not doing this.)

I've run into the same problem because I wanted to use dots in my entity names (to mirror filenames with extensions), which caused issues both with the explorer and even entity creation, as dots are used as separators by default. Thankfully Sander introduced a way to avoid tokenization.

**Comment by SanderMertens** [comment]
Yep, that's exactly it. Because the explorer is fully built on top of the (string based) query DSL, it is usually the first place where these problems show up.

I'm experimenting with some code that lets me use entity names with spaces since this comes up so often, may be able to check in a fix that adds support for it.
