### ISSUE TITLE
ecs_set() doesn't work C

### ISSUE THREAD

**Issue by mshlmao** [SanderMertens/flecs#1217]
I'm following show me the code from:
https://www.flecs.dev/flecs/index.html#show-me-the-code

but ecs_set() function does not work
initially I thought it could be a problem with my component but when I tried to use ecs_add() it worked.

this is the error I'm getting:
![image](https://github.com/SanderMertens/flecs/assets/130911884/4e2f6d11-7074-482b-bc47-c1bed797ec71)

is it a problem with macro or am I doing something wrong?

**Comment by copygirl** [comment]
Are you compiling this as C or C++? Some C syntax doesn't work in C++. I remember Sander explaining this somewhere, might've been in the issues, might've been in Discord. However I did find a related message that noted that simply replacing `{ ... }` with `Type{ ... }` (where `Type` is the component type you're trying to set) resolved the issue.

By the way, pasting the error message(s) in the issue description rather than just a screenshot (providing both is fine) allows searching for the error message in related issues, so please keep that in mind for future issues you create.

**Comment by mshlmao** [comment]
> Are you compiling this as C or C++? Some C syntax doesn't work in C++. I remember Sander explaining this somewhere, might've been in the issues, might've been in Discord, though I wasn't able to find it. However I did find a related message that noted that simply replacing `{ ... }` with `Type{ ... }` (where `Type` is the component type you're trying to set) resolved the issue.
> 
> By the way, pasting the error message(s) in the issue description as text rather than just a screenshot (providing both is fine) allows searching for the error message in related issues, so please keep that in mind for future issues you create.

I'm not sure if that's what you meant but it doesn't solve the problem. 
I'm getting: 
Error	C2102	'&' requires l-value	

With this code
![image](https://github.com/SanderMertens/flecs/assets/130911884/c514a550-3a01-40c8-978f-ea95ff38347f)

My custom VS settings are:
Disable language extensions: yes(/za)
Compile as: Compile as C code

Should I change something else?

**Comment by copygirl** [comment]
If the code is being compiled as C then the original code should work.
Can you share more of your code?

**Comment by mshlmao** [comment]
> If the code is being compiled as C then the original code should work. Can you share more of your code?

So I think I figured the problem. My engine.h which used ecs_set function was a header and seems like it is causing the issue. Probably obvious for everyone but I'm new in the C world.
