### ISSUE TITLE
clang-20 - compilation error 😢

### ISSUE THREAD

**Issue by alexv-ds** [SanderMertens/flecs#1311]
**Describe the bug**
Compilation error
```console
addons/cpp/utils/enum.hpp:240:33: error: no matching function for call to 'to_int'
```

**To Reproduce**
1. Get [sample.zip](https://github.com/user-attachments/files/16645054/sample.zip)
2. Compile it

**Additional context**
tested on - clang-20, ubuntu-24.04

**Comment by apache-hb** [comment]
I've also hit this and have a bit more context as to why this has become an issue.

`to_int` casts an integer to an enum value, clang incorrectly used to allow any integer value to be cast to an enum value at compile time, since 20 clang now refuses to instantiate enum values at compile time with a value not in the representable bit range of enum values. C++ (since 20?) specifies that enums are at least as large as the minimum number of bits required to represent all values in 2s complement.

This means its no longer enough to use FLECS_ENUM_MAX(E)` as an upper bound, some other way will need to be used to prevent going out of range. `std::numeric_limits<std::underlying_type_t<E>>` won't be enough because it'll round up to the nearest 8 bits, and even going 1 bit out of range triggers this compiler error.

**Comment by SanderMertens** [comment]
magic_enum ran into the same issue, this looks like a potential fix:
https://github.com/Neargye/magic_enum/blob/master/include/magic_enum/magic_enum.hpp#L626

**Comment by SanderMertens** [comment]
Fixed!
