### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [SanderMertens/flecs#15]
Would you like to add more error handling for return values from functions like the following?
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [ecs_array_new](https://github.com/SanderMertens/flecs/blob/bb5236fc7a9e01ca78f31493dcb4eca7d48b3125/src/array.c#L52)
- [printf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output") ⇒ [load_admin](https://github.com/SanderMertens/flecs/blob/d0ffcea6c98d71050061e1654215aa0d33547bd6/src/world.c#L445)

**Comment by SanderMertens** [comment]
Yes, definitely. Since I have your ear, I'd like to do a more comprehensive review of error handling. Today the API asserts when there is an error, and you get the file + line where the assert happened. Often that is sort of useful, but you don't really know where the error happened in your app code.

I'd like to move the actual assert to a macro that wraps the API, so that the assert reports the location in the application code, not in the library. That could make it much easier to debug things, as I don't need another tool to obtain the stack trace to see where it happened. Additionally, if you would use the "unwrapped" API, you'd have an API that never asserts, so you kind of have the best of both worlds.

Anyway, that's just an idea I thought would make life a little bit easer. Curious to hear what people think.

**Comment by elfring** [comment]
* I find [the macro name “assert” suspicious for the mentioned use case](https://wiki.sei.cmu.edu/confluence/display/c/PRE31-C.+Avoid+side+effects+in+arguments+to+unsafe+macros#PRE31-C.Avoidsideeffectsinargumentstounsafemacros-NoncompliantCodeExample%28assert%28%29%29 "Avoid side effects in arguments to unsafe macros.").
* I suggest to reconsider the wrapping imaginations.

-----

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by SanderMertens** [comment]
@elfring Ok, I will reconsider that. For now, I will stick with the current approach, and address the issues you identified.

**Comment by SanderMertens** [comment]
I added a more complete description of error handling here: https://github.com/SanderMertens/flecs/blob/master/Manual.md
