### ISSUE TITLE
system_runner_fluent::filter() and .exclude<T>()

### ISSUE THREAD

**Issue by drywolf** [SanderMertens/flecs#160]
I am experimenting and learning about the C++ flecs API and just now I looked into flecs::system::run().filter() of the [23_get_children](https://github.com/SanderMertens/flecs/blob/master/include/flecs/flecs.hpp#L1153) example.

Then I tried to add an additional `exclude<Bar>()` clause one of the filters, but as it turns out this is [explicitly](https://github.com/SanderMertens/flecs/blob/master/include/flecs/flecs.hpp#L1153) not supported. I tried the same with an extra `include<Bar>()` clause and indeed the result was as expected, the system only ran on the one of the parents' children that had the Bar component.

@SanderMertens Is there some architectural / technical reason why `exclude<T>()` is not supported at this part of the API or is it just not implemented yet?
I would go ahead myself and attempt to add this feature if there is nothing against it.

**Comment by drywolf** [comment]
PS: In the example I now also tried adding `!Bar` to the system signature, which should achieve the same as `filter.exclude<Bar>()` to my understanding, and indeed this seems to work.
That makes it even more odd that the supposedly same exclusion clause works in `signature()` but does not work with `.filter()`

**Comment by SanderMertens** [comment]
@drywolf There is no real architectural reason why this doesn't work, all the logic to support this is implememted. The only reason why this hasn't been implemented yet is because the underlying C API to run a system (`ecs_run_w_filter`) predates the include/exclude filter concept, and to change that would mean a breaking API change, and a major version increase.

Long term I will break the API compatibility to address this. For now I agree that this is annoying (I actually ran into the same problem myself not too long ago). I will look into implementing a temporary `ecs_run` function that supports an `ecs_filter_t`.

**Comment by drywolf** [comment]
Thanks for the clarification

**Comment by SanderMertens** [comment]
I added the exclude filter to the C++ API. This functionality is also available in the C API using the `ecs_run_w_filter_v2` function. In the next major release the v1 function will be updated to this new signature.
