### ISSUE TITLE
Clear up section of manual on entity identifiers used for components / systems

### ISSUE THREAD

**Issue by cc861010** [SanderMertens/flecs#166]
**Describe the bug**
Systems and components (amongst others) obtain identifiers from the same id pool as entities, thus handles to systems and components are also of type ecs_entity_t. Types are vectors of entity identifiers that are used to describe which components an entity has (components are identified by entity identifiers), amongst others.

Could you rewrite these sentences with more straightforwd sentences?
what is the same id pool as entities?
what are vectors of entity identifiers?

**Comment by SanderMertens** [comment]
@cc861010 I just wrote a blog about this:
https://medium.com/@ajmmertens/building-an-ecs-1-types-hierarchies-and-prefabs-9f07666a1e9d

Basically what it means is, components and systems are internally stored as entities, which is why the a component / system handle is of type `ecs_entity_t`.

"obtain identifiers from the same id pool as entities"
Each time you create a new entity it gets a unique id. Because systems and components are implemented as entities, their ids get generated the same as ordinary entities.

"what are vectors of entity identifiers?"
A vector as in the data type, as if I would do `vector<ecs_entity_t>`.

I'll try to clear up this section of the manual.

**Comment by SanderMertens** [comment]
The manual has been rewritten, so closing this issue.

This section now explains the above:
https://github.com/SanderMertens/flecs/blob/master/docs/Manual.md#component-handles
