### ISSUE TITLE
Question: scale

### ISSUE THREAD

**Issue by scriptslol** [SanderMertens/flecs#21]
Hi @SanderMertens, 

I recently discovered flecs and i've been exploring your other work as well.  

What are your thoughts on networking(ipc)?  

Furthermore, bake and corto look really interesting as well. I'm curious if you've ever done any simulation testing at large and/or distributed scales?

In comparison, platforms like SpatialOS are enabling a lot more game devs & designers to work at a larger scale via data oriented approaches. But, I feel like there's another layer of resolution that is yet to be obtained and it collapses a LOT of problem spaces... Mainly in the realm of Game/Data Engineering, Design, Analytics, Machine Learning and Business Insights.

 I'm still experimenting so i'll see how far this rabbit hole goes with zmq, corto, flecs and dear imgui :)

(extending windows right click with contextual: bake/flecs sub-commands was a worthwhile effort!)

**Comment by SanderMertens** [comment]
Hi @scriptslol, currently Flecs is being used in a prototype for a distributed simulation project that is based on OMG-DDS. It is still a work in progress, with things to address such as:

- Time synchronization between nodes
- Rollback simulation when necessary (#7)
- Distribute entities across machines (especially for "hard" problems, like collision detection)

Besides realizing horizontal scalability, another goal is to ensure reusability of the created applications so that they can be used by systems with different configurations and deployments. The idea is to compose a discoverable external interface out of ECS components (similar to how systems are defined), and use this to "pull" data out of the ECS applications. That way a system designer can decide which components should be distributed and which components should remain local.

> (extending windows right click with contextual: bake/flecs sub-commands was a worthwhile effort!)
That sounds really cool! Is that available in a public repository?

**Comment by scriptslol** [comment]
Sorry for a delay in my response, I really appreciated your response and I've been reflecting on it :)

I use EC Menu 1.6 - I don't use any of the built-in commands. I just setup custom commands that invokes a simple cli that carries out the given command. As an example parameter in EC Menu:

Program: C:\tools\toolbelt.cli.exe
Parameter: -cmd setup -path "%V"    (or %1 for specifically right clicked files/folders)

In regards to your prototype with OMG-DDS;  It's a very fun problem to solve! 

Solid data oriented infrastructure is exciting. Can't wait to see how all of our industries grow and collapse into a singularity, lol.

**Comment by teksoc-1** [comment]
Hi @SanderMertens , I see this issue was recently closed - yet see that you were working ( or done? ), via the OMG-DDS project you mentioned. I'm really interested in leveraging flecs in a distributed manner - across process boundaries would be great, and across machines would be awesome! As an interim solution, building off the standard flecs API, we built out a PoC Messaging Module to serve as a bridge for one flecs instance in one process to another, but it's not at all the distributed flecs we are really seeking to achieve. Anyways do you have any more info/resources/repos/thoughts on this subject?

**Comment by SanderMertens** [comment]
@teksoc-1 This is an evolving topic. What I did was create a few systems that matched with the components I wanted to distribute, and send those in bulk over the network. Writing to the network was really fast, as I could use the component arrays directly in sending the data. For reading back and inserting the data there now is the `ecs_set_w_data` API which will make the reading side very efficient as well, provided you insert the same set of entities repeatedly.

However, a full distributed solution should also include the above topics (time management, rollback, load balancing). I'm curious what you did in your project, if you can, please share your approach!

**Comment by teksoc-1** [comment]
@SanderMertens Our PoC  Messaging Module was simply a proxy to transport messages of a raw data buffers, not necessarily ECS type data. At a high level, the Messaging Module would create Send/Receive Channel components that other modules could utilize for messaging. A sender would add SendChannel,Message components to an entity that the Messaging Module would send along to a remote Messaging Module in a remote process. In that remote process, the real intended recipient (system) would subscribe for ReceivedMessage,SomeUniqueTag that the Messaging Module would throw out into the world. It was a poor man's solution I guess, but it was really our first cut at learning ECS, and exercising the Flecs API. At first we weren't even sure ECS was the appropriate architecture, but non-game projects adopting an ECS architecture such as the following were found to be inspiration to try something a little unorthodox: 

https://appleinsider.com/articles/19/03/06/apples-videogame-routines-used-to-protect-users-from-viruses-and-malware-in-new-utility

The article mentions GamePlayKit - Apple's native ECS implementation, however we were looking for a cross platform framework in pure C to extend beyond the Apple ecosystem ... and that's where I stumbled upon Flecs.

Will take a look at `ecs_set_w_data` ...

**Comment by teksoc-1** [comment]
@SanderMertens Do you have any particular suggestions for implementing client/server patterns in Flecs i.e. Module X provides some service say for example `HandleRequestSystem(Request)`  where the implementation may either add a Response component to entities, or generate new entities with Response components - service side implementation is really orthogonal to the 'problem'.  This 'problem' that we see is ensuring the correct client (system) only receives the appropriate filtered Responses for the Requests that it made - doesn't care about any other Responses to Requests it didn't generate. Our naive approach to this problem is to leverage unique Tags that we would add to entries, and thus filtering for `MyResponseSystem(Response, MyUniqueTag)` ... is there a better way to do this, are we not thinking about this the ECS way, etc?

**Comment by SanderMertens** [comment]
@teksoc-1 - I created a separate issue for this question: #71
