### ISSUE TITLE
Multiple worlds don't all run at the desired FPS rate

### ISSUE THREAD

**Issue by mgerl** [SanderMertens/flecs#225]
**Describe the bug**
I created 3 worlds, set to fps rates of 1, 10, 100.... each with a single system running once per iteration/frame. When I run a loop for 10 seconds with each one of them progressing, I only get 12 hits to the 100fps world. If I only progress world 3 (100fps) by itself - I get 998 iterations (close to the 1000 expected -- 10 sec @ 100 fps). This seems like a bug -- or am I missing something?

**To Reproduce**
C++ (similar to example 40 - without the task component)
Create 3 worlds each with 1 system .action and a single cout statement
Set the worlds to 1, 10, 100 fps
Loop for some number of seconds, calling .progress() for each one (any order)
Count the cout statements (hint: grep -c WORLD2)

**Expected behavior**
If I run the loop for 10 seconds, I should have ~10 World1, ~100 World2, and ~1000 World3 cout statements. Instead I get ~10 for each.

**Additional context**
C++ on Windows using Visual Studio 2019.

**Comment by SanderMertens** [comment]
@mgerl Are you calling the `progress` calls in the same loop/thread?

The FPS limiter works by inserting sleeps in the `progress` call, to slow down the application in case it is progressing at a higher FPS than what is set by the application. That means that if you run 3 worlds with 3 different FPS settings in the same loop, they will all run at the lowest setting, since the 1 FPS world will slow down the loop to just one cycle a second.

If this is the case, and you want to run your three worlds at the different FPS settings, you would have to use different threads. Another solution would be to use one world, and different time intervals for your systems.

**Comment by mgerl** [comment]
Hi!!

I’m very interested in using threads - but when I tried set_threads() I get an abort looking for thread_new() or something. I can’t find thread docs or a sample — am I missing something?

I’m in serious eval-mode for an important simulation system v2.0; we are looking at for a major company. I’m really trying to understand timings and capabilities. We have to simulate complex satellites with some components running at 200Hz or faster.

Any guidance on getting started with threads is super welcome!!!

Thanks!!
Mark

-- 
Mark D. Gerl, mobile: 703-829-6275

**Comment by SanderMertens** [comment]
Sounds like an awesome project!

To clarify my earlier statement:
> you would have to use different threads

I meant calling `progress()` from different, application managed threads, so that the slowest call to `progress()` won't hold up the other worlds.

>  I get an abort looking for thread_new()

That's right- Flecs doesn't come with an operating system abstraction API out of the box, which means you have to provide your own thread functions. Look at `include/flecs/os_api.h` and `addons/os_api_impl.c` for more information.

> I’m really trying to understand timings and capabilities

I'm still adding to the docs! In the meantime, feel free to join the Discord where I can answer questions in realtime: https://discord.gg/MRSAZqb

**Comment by mgerl** [comment]
I would seriously consider this a bug -- if a decision is made to set the speed of the main event loop down to the slowest FPS of all the worlds that are using .progress() in it on that thread, the loop should at least run as fast as the highest FPS amongst the worlds.

But, appreciate the info. Thanks!

**Comment by mgerl** [comment]
one justification here ... consider this main event loop...

```
world1.set_target_fps(1);
world2.set_target_fps(100);
while (true)
{
    DoSomeFastStuff();
    world1.progress();
    world2.progress();
    DoOtherFastStuff();
}
```
Regardless of how world1 and world2 are specified, they should never slow down processing. Each world should do their own thing, as fast as they can, and get on. As long as the `world` object is not a singleton, the abstraction should be there.

Please consider.

**Comment by SanderMertens** [comment]
@mgerl I understand your point, but the mechanism whereby this is implemented doesn't allow for running different worlds at different speeds in the same thread. `world.progress()` is a blocking call, and the only mechanism I have to slow down the application if it runs to fast is to insert sleeps in `progress()`. Any other approach (like only calling systems when enough time has passed) would result in the main loop spinning as fast as it can until it saturates the CPU.

So I don't consider this a bug, it's just not possible to implement it in any other way, unless you'd have to build cross-world coordination which I also don't want to do, since each world needs to be fully separated. Consider, what if you _would_ run the worlds in different threads, but you would have them negotiating the sleep time, that would be no good.

There are a few solutions to this problem. Perhaps the easiest one is to only enable FPS limiting for the fastest world, and manually keeping track of time passed for each of the slower worlds, and only invoke `progress()` when enough time has passed.

The other solution is to enable time intervals for systems inside worlds.

**Comment by mgerl** [comment]
OK ok ok ... I will concede; it's by design and not a bug. I do appreciate the options here ... by removing the attempts at putting each world on a target fps, they all can run at full speed (and ping the processor) - and each system can run on the desired .period() to achieve the test results.

Thanks! We can close this non-bug.
