### ISSUE TITLE
Documentation regarding multithreading support is missing

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#281]
Hello! First of all, thank you for a wonderful library. I was searching for references to implement my own ecs (using archetypes + lock-free parallelism for system execution), but looking through **flecs** examples it appeared to me that you already solved all my use-cases. So not only you are a perfect reference, but also a viable candidate for drop-n-use. 

The only problem for me is being unable to verify the ability of **flecs** to utilize multiple cores. Namely, there are no details in the docs/ and there are no examples (that I could find) showing how one system writes to components A, and other system reads them, thus being executed sequentially relative to the first one, but parallel to other read-only consumers of those components (stuff described, for example, here https://youtu.be/3N1pLtTV2Uc?t=3621 ).

There is a note in readme, and it promises a lot, but it is hard to verify it in code and find any documentation regarding this feature: `Lockless threading design allows for efficient execution of systems on multiple threads`

So my suggestion is to add some details to the manual, or add an example showing off this concept in your codebase, if it really exists. Nonetheless I am going to analyze your code to see its capabilities in the near future! King regards!

**Comment by SanderMertens** [comment]
Good point, I'll try to prioritize this.

In the meantime, this may help:

The threading design is actually quite simple. It relies on creating a number of worker threads (with the `ecs_set_threads` function). When you run systems (using the `ecs_progress` function) entities matched with a system will be divided equally across threads.

You can add/remove components to entities from multiple threads, these changes are stored in a command queue until they're merged at the end of the frame. This part of the manual explains how this works in more detail:
https://github.com/SanderMertens/flecs/blob/master/docs/Manual.md#staging

If you want to use threading, you need to set the OS API functions for creating/deleting threads, mutexes, condition variables etc. This project does this for you: https://github.com/SanderMertens/flecs/tree/master/examples/os_api/flecs-os_api-posix

This project uses Flecs multithreading (it's a bit outdated, but you should be able to see from the code what's going on):
https://github.com/SanderMertens/ecs_nbody

Hope that helps! I'll keep the issue open until the docs are added :)

**Comment by Hexlord** [comment]
Great, thank you for the information, it is indeed helpful! 

I was thinking that the overwhelming number of systems (in a real-world game, not an n-body simulation showcase) makes it not worth to parallelize single system execution due to: cache line transfer fee, memory underutilization (spending more time on CPU with multiple threads when we could already enqueue memory transfers for other systems data), and thus one should parallelize systems themselves, while preventing concurrent r/w to shared components thus negating any need in synchronization point (concurrent access to same columns never happens). 

As I understood "Staging" from the manual, you by default postpone any entity creation and archetype mutation (for obvious reasons), great stuff, but the merging might indeed incur a cost. I wonder if replacement of threads with lightweight fibers and immediate mutation of archetype tables under per-archetype locks could lead to performance improvement (invalidated iterators are not an issue as we could just traverse some copy of a vector of matched entity ids ignoring invalidated/missing ones, thus also ignoring created ones - which is okay).

**Comment by SanderMertens** [comment]
> I was thinking that the overwhelming number of systems (in a real-world game, not an n-body simulation showcase) makes it not worth to parallelize single system execution

Actually, it can become _more_ worthwhile to multithread when you have lots of systems :) Flecs only has a single synchronization point by default, which is at the end of the frame. This means that a thread will run all systems to completion before synchronizing with other threads.

This is safe, because it is guaranteed that each entity will be processed by the same thread. For each archetype, I split up the entities across threads. If the entities in an archetype don't change (they won't since operations are deferred), the allocation of entities to threads doesn't change.

> Actually we iterate dense set, so creating entities during the frame would add new entries to the back, which should not cause any trouble at all for the iterators

This would be true if it weren't for two reasons:

1) Reallocs. If you need to grow an array because of adding a new entity, you're screwed
2) You're still mutating shared state (the table count) which other threads could be reading

**Comment by Hexlord** [comment]
> Actually, it can become more worthwhile to multithread when you have lots of systems :) Flecs only has a single synchronization point by default, which is at the end of the frame. This means that a thread will run all systems to completion before synchronizing with other threads.

Oh, True, so you utilize the thread cache the best way possible - keeping its set of entities static. Smart!

> This would be true if it weren't for two reasons:
> 
> 1. Reallocs. If you need to grow an array because of adding a new entity, you're screwed
> 2. You're still mutating shared state (the table count) which other threads could be reading

I was thinking you could solve Realloc issue by always keeping the storage half-empty, or something. Realloc in advance. But that is wonky indeed. Maybe have much empty space AND provide a fallback mechanism like deferred std::function wrapping of executed lambda (which contains entity creation code). It is extremely slow, but it should nearly never happen, so may be it is worthy for the win in the simplicity of the architecture. Yes, not selling this one :)

Table counts could be cached at the beginning of the frame, I do not think it is much of an issue.

**Comment by SanderMertens** [comment]
> Table counts could be cached at the beginning of the frame, I do not think it is much of an issue.

That's true. However:

One thing that I just thought of that would be harder to cache though is the entity index (the thing that maps entity ids to their tables). In flecs this is implemented as a sparse set, and adding/updating an entry for a new entity is not thread safe.

Another potential problem is that entities rarely get added to their destination table. Usually when an entity is created, a bunch of components are added one-by-one. You could argue that this is okay, because entities are added to the end of their tables, and when you add, you remove an entity from the end and append it to the end of another table, but it definitely feels a bit wonky 😅

You could also only do this from a single thread. When multiple threads add to the same table, things break.

Additionally, since you'd be caching the table counts, the entity wouldn't be processed by any systems anyway. It sounds like you'd be doing a lot of work for little benefit.

**Comment by Hexlord** [comment]
> One thing that I just thought of that would be harder to cache is the entity index (the thing that maps entity ids to their tables). In flecs this is implemented as a sparse set, and adding/updating an entry for a new entity is not thread safe.

Yep, that would incur a costful lock.

> Another potential problem is that entities rarely get added to their destination table. Usually when an entity is created, a bunch of components are added one-by-one. You could argue that this is okay, because entities are added to the end of their tables, and when you add, you remove an entity from the end and append it to the end of another table, but it definitely feels a bit wonky 😅

I feel this should only happen in development, an in-game all you do is clone entities (prefabs). I mean one could live without runtime archetype construction.

> You could also only do this from a single thread. When multiple threads add to the same table, things break.

Yep, adding to the table is not atomic indeed, which means it also requires a lock.

> Additionally, since you'd be caching the table counts, the entity wouldn't be processed by any systems anyway. It sounds like you'd be doing a lot of work for little benefit.

Yes, so it would act just like postponed entity creation. I was hoping there is something to win performance-wise, but now I see it is futile! 

Well that was enlightening. I have no idea how to improve on your multithreading, which makes perfect sense 😅. Thanks for dedicating your time!

**Comment by SanderMertens** [comment]
> Well that was enlightening. I have no idea how to improve on your multithreading, which makes perfect sense 😅. Thanks for dedicating your time!

Oh, there's many improvements that can still be made! Arguably the most important thing that needs to be added is the ability to bind a system to a single thread (especially important for things like render systems). This does make the whole design quite a bit more complicated though, because it would violate the allocation of an entity to a thread.

If you'd like to discuss this more, feel free to join the Discord :)
