### ISSUE TITLE
High CPU usage when target framerate is set

### ISSUE THREAD

**Issue by mjjq** [SanderMertens/flecs#290]
When ecsworld.set_target_fps(60.0) is called, I get CPU usage on the order of ~10% even for trivially simple ecs worlds. This happens even with the -O2 optimisation flag applied.

I have compared my code (see snippet below) with and without a target fps defined using gprof. It appears that the main CPU hog is `ecs_os_time_now` with a bunch of other time related functions to go with it. Here are the top 15 or so function calls from each scenario:

**NO fps limit**
```
Flat profile:

Each sample counts as 0.01 seconds.
 no time accumulated

  %   cumulative   self              self     total           
 time   seconds   seconds    calls  Ts/call  Ts/call  name    
  0.00      0.00     0.00   267011     0.00     0.00  _ecs_assert
  0.00      0.00     0.00    69929     0.00     0.00  _ecs_vector_copy
  0.00      0.00     0.00    44359     0.00     0.00  _ecs_vector_first
  0.00      0.00     0.00    43206     0.00     0.00  ecs_vector_count
  0.00      0.00     0.00    24402     0.00     0.00  _ecs_vector_get
  0.00      0.00     0.00    16509     0.00     0.00  ecs_type_find
  0.00      0.00     0.00    12469     0.00     0.00  ecs_table_notify
  0.00      0.00     0.00    10134     0.00     0.00  _ecs_sparse_get
  0.00      0.00     0.00    10032     0.00     0.00  ecs_filter_next
  0.00      0.00     0.00     7970     0.00     0.00  ecs_os_gettime
  0.00      0.00     0.00     7495     0.00     0.00  ecs_get_stage
  0.00      0.00     0.00     6139     0.00     0.00  ecs_os_has_modules
  0.00      0.00     0.00     5606     0.00     0.00  _ecs_sparse_get_sparse
```

**60 fps limit**
```
Flat profile:

Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total           
 time   seconds   seconds    calls  us/call  us/call  name    
 21.57      0.44     0.44                             _mcount_private
 17.16      0.79     0.35 16803909     0.02     0.02  ecs_os_time_now
 17.16      1.14     0.35                             __fentry__
 12.25      1.39     0.25 16803608     0.01     0.06  ecs_time_measure
  9.31      1.58     0.19 16803608     0.01     0.01  ecs_time_to_double
  7.60      1.74     0.16 16811878     0.01     0.03  ecs_os_gettime
  6.37      1.87     0.13                             insert_sleep
  4.90      1.97     0.10 16803608     0.01     0.01  ecs_time_sub
  1.47      2.00     0.03     2674    11.22    14.96  ecs_sleepf
  0.49      2.00     0.01 17070923     0.00     0.00  _ecs_assert
  0.49      2.02     0.01     2674     3.74     3.74  ecs_os_time_sleep
  0.49      2.02     0.01      300    33.33    33.33  flecs::world::progress(float) const
  0.49      2.04     0.01                             eval_component_monitor
  0.25      2.04     0.01                             ecs_os_err
  0.00      2.04     0.00    69929     0.00     0.00  _ecs_vector_copy
  0.00      2.04     0.00    44359     0.00     0.00  _ecs_vector_first
```

**To Reproduce**
1) Open task manager or a similar CPU monitoring tool.
2) Copy the below code into a new file, build and run.
3) As the program is running, you should notice the CPU usage in task manager spike. The CPU usage increases to ~10% (though this may vary depending on your CPU)
```
#include <stdio.h>
#include <string>

#include "flecs.h"

struct Position
{
    float x;
    float y;
    float z;
};
struct Physics{};

void performanceTest()
{
    flecs::world ecsWorld;
    ecsWorld.set_target_fps(60.0f);
    
    ecsWorld.component<Position>();
    ecsWorld.component<Physics>();
    
    for(unsigned int i=0; i<1; ++i)
    {
        auto e = ecsWorld.entity(std::to_string(i));
        e.add<Position>();
        e.add<Physics>();
    }
    
    ecsWorld.system<Position, Physics>("Physics")
        .iter([](flecs::iter& it, Position* p, Physics* phys)
    {
        for(auto i : it)
        {
            p[i].x += 0.1f;
            p[i].y += 0.1f;
            p[i].z += 0.1f;
        }
    });
    
    for(int i=0; i<300; ++i)
    {
        ecsWorld.progress(0.1f);
    }
}

int main()
{
    performanceTest();
    
}
```

**Expected behavior**
There should be almost 0% CPU usage.

**Additional context**
My CPU is an i5 2500K @ 3.8GHz, running Windows 10 LTSE. The above code was compiled with g++ (MinGW):

**Comment by randy408** [comment]
This is due to the way timer accuracy is measured before it falls back to a busyloop.

https://github.com/SanderMertens/flecs/blob/9338695b5d0eac47d24286eb3bfed318bf046dee/src/world.c#L887-L890

The target sleep duration is divided by `20` and the sleep error is measured, but Windows timers typically sleep for at least 1-2 ms, so a sleep duration of  `16.67 / 20  = 0.83` ms (60fps) will cause flecs to switch to a busyloop early on.

**Comment by SanderMertens** [comment]
I'm starting to think the busy loop is causing more trouble than it's worth. I may just remove it entirely. If the sleep accuracy on a system is really that bad, there isn't much that the library can do without resorting to draconian measures.

That will mean that on some platforms where the accuracy is high enough `delta_time` will fluctuate more. Applications that require higher accuracy can always implement their own sleep algorithm(s) and pass a `delta_time` value to the `progress` function.

**Comment by SanderMertens** [comment]
I checked in a fix for this, which basically removes the tryharding from the set_target_fps function to be accurate, and rather have the behavior be predictable. I removed the busy loop, so the CPU should no longer end up spinning.

As a result of this change, you may observe that set_target_fps is less accurate. On some platforms (and specifically in VMs) the behavior of a sleep is erratic (sleeping for 0.01s can cause waiting up to 0.2s), and using a single sleep statement can already overshoot the target. The previous implementation detected and kept track of the sleep error, and adjusted the time it would sleep accordingly.

However, on platforms with a totally unpredictable sleep, this could cause the code to always default to a busy wait loop (a while that checks elapsed time until enough time has passed). While very accurate, this is rarely what you want when using this function.

The new implementation calculates how much time has elapsed since the last frame, computes how much time it needs to sleep, divides that number by some constant, and call sleep with the resulting value in a loop until roughly enough time has passed.

If more accuracy is needed, an application can always override the OS API sleep_ function. This enables an application to plugin the old behavior if desirable.
