### ISSUE TITLE
Recreating a world in Unreal can cause issues with component identifiers

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/flecs#293]
**Describe the bug**
Multiple users have reported than after destruction and recreation of a world, issues arise in the C++ API that can be solved by manually resetting the component identifier (using the internal `reset` method).

**To Reproduce**
TBD, world recreation seems to cause it, but unknown what is exactly causing the issue.

**Expected behavior**
World recreation should work seamlessly.

**Comment by jtferson** [comment]
The same issue we obviously have with importing modules in Unreal. By design a module is loaded only once, so after execution of the hot reloading by Engine the crash is under way if some module's components are used in systems. It seems the only option is somehow resetting all static data inside Flecs after a manual destruction of one or more Flecs worlds (or may be an API method to reset Flecs).

**Comment by SanderMertens** [comment]
I think I have a solution for the issue. To fix it, I had to change the `EcsName` component so that the `symbol` member now requires an allocation. Code that uses `set<EcsName>` will not be affected, but code that manually updates the component value with `get_mut` must change.
