### ISSUE TITLE
Rename world to registry

### ISSUE THREAD

**Issue by FedorLap2006** [SanderMertens/flecs#331]
Name of registry for entities and systems is a bit confusing. Yes, I agree that `world` is still recognizable, but `registry` will be nicer. Because it fits better with the whole concept of containing entities and systems in some "world".

**Comment by SanderMertens** [comment]
This would be a very large change that would impact all code ever written with Flecs :) Additionally, the name "world" is has become somewhat of a convention in ECS. Here are a few other frameworks that also use "world":

- https://github.com/amethyst/legion
- https://github.com/ecsyjs/ecsy
- https://github.com/Ralith/hecs
- https://github.com/leudz/shipyard
- https://github.com/amethyst/specs

I do not see any objective disadvantages to using "world", so I think it comes down to preference. Because of this, I will close the issue.
