### ISSUE TITLE
Importing module twice results in duplicate component errors.

### ISSUE THREAD

**Issue by artgreen** [SanderMertens/flecs#337]
**Describe the bug**
Importing module twice results in duplicate component errors.

**To Reproduce**

```
#include <iostream>
#include <flecs.h>

namespace namespace_a {
    struct TagA {};
    struct ModuleA {
        ModuleA(flecs::world &ecs) {
            ecs.module<namespace_a::ModuleA>();
            ecs.component<namespace_a::TagA>();
        }
    };
}

namespace namespace_b {
    struct TagB {};
    struct ModuleB {
        ModuleB(flecs::world &ecs) {
            ecs.module<namespace_b::ModuleB>();
            ecs.component<namespace_b::TagB>();

            ecs.import<namespace_a::ModuleA>();

            flecs::entity e = ecs.entity("EntityA").add<namespace_a::TagA>();
            std::cout << e.name() << std::endl;
        }
    };
}

int main(int argc, char *argv[]) {
    flecs::world ecs(argc, argv);

    flecs::world::enable_tracing(2);

    // Import modules
    ecs.import<namespace_a::ModuleA>();
    ecs.import<namespace_b::ModuleB>();
    return 0;
}
```

**Expected behavior**
Per the manual: "A module is only loaded once, regardless of how many times an application imports it."  Thus, EntityA should be printed to the console.
  
Instead this error message appears:
"err : | | assert(!strcmp(path, name)) /usr/local/include/flecs/flecs.hpp:3737: component redefined with a different name (namespace_a::TagA)"

If the following lines are commented out, the program runs without error:
//            ecs.component<namespace_a::TagA>();
...
//            flecs::entity e = ecs.entity("EntityA").add<namespace_a::TagA>();
//            std::cout << e.name() << std::endl;

**Additional context**
The above code sample is in one file for demonstration purposes.  This issue first showed up when I had the modules in different files, so, the fact that the above code is all in main.cpp the issue should still be accurately shown.

info: import namespace_a::ModuleA
info: | table [Name,CHILDOF|namespace_a] created
info: | table [EcsComponent,Name,CHILDOF|namespace_a] created
info: | table [CHILDOF|namespace_a.ModuleA] created
info: | table [Name,CHILDOF|namespace_a.ModuleA] created
info: | table [Name,CHILDOF|namespace_a.ModuleA.namespace_a] created
info: | table [Name,CHILDOF|namespace_a.ModuleA,CHILDOF|namespace_a.ModuleA.namespace_a] created
info: | table [EcsComponent,Name,CHILDOF|namespace_a.ModuleA,CHILDOF|namespace_a.ModuleA.namespace_a] created
info: | table [EcsComponent,Name,namespace_a.ModuleA,CHILDOF|namespace_a] created
info: import namespace_b::ModuleB
info: | table [Name,CHILDOF|namespace_b] created
info: | table [EcsComponent,Name,CHILDOF|namespace_b] created
info: | table [CHILDOF|namespace_b.ModuleB] created
info: | table [Name,CHILDOF|namespace_b.ModuleB] created
info: | table [Name,CHILDOF|namespace_b.ModuleB.namespace_b] created
info: | table [Name,CHILDOF|namespace_b.ModuleB,CHILDOF|namespace_b.ModuleB.namespace_b] created
info: | table [EcsComponent,Name,CHILDOF|namespace_b.ModuleB,CHILDOF|namespace_b.ModuleB.namespace_b] created
info: | import namespace_a::ModuleA
err : | | assert(!strcmp(path, name)) /usr/local/include/flecs/flecs.hpp:3737: component redefined with a different name (namespace_a::TagA)

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by artgreen** [comment]
I'm stupid - Here is a cleaner example of the issue I'm seeing.
```

#include <flecs.h>

namespace namespace_a {
    struct TagA {};
    struct ModuleA {
        ModuleA(flecs::world &ecs) {
            ecs.module<namespace_a::ModuleA>();
            ecs.component<namespace_a::TagA>();
        }
    };
}

int main(int argc, char *argv[]) {
    flecs::world ecs(argc, argv);

    flecs::world::enable_tracing(2);

    // Import modules
    ecs.import<namespace_a::ModuleA>();
    ecs.import<namespace_a::ModuleA>();
    return 0;
}

```
info: import namespace_a::ModuleA
info: | table [Name,CHILDOF|namespace_a] created
info: | table [EcsComponent,Name,CHILDOF|namespace_a] created
info: | table [CHILDOF|namespace_a.ModuleA] created
info: | table [Name,CHILDOF|namespace_a.ModuleA] created
info: | table [Name,CHILDOF|namespace_a.ModuleA.namespace_a] created
info: | table [Name,CHILDOF|namespace_a.ModuleA,CHILDOF|namespace_a.ModuleA.namespace_a] created
info: | table [EcsComponent,Name,CHILDOF|namespace_a.ModuleA,CHILDOF|namespace_a.ModuleA.namespace_a] created
info: | table [EcsComponent,Name,namespace_a.ModuleA,CHILDOF|namespace_a] created
info: import namespace_a::ModuleA
err : | assert(!strcmp(path, name)) /usr/local/include/flecs/flecs.hpp:3737: component redefined with a different name (namespace_a::TagA)

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by SanderMertens** [comment]
Thanks for reporting!

Checked in a fix. The issue was that in the module registration code two different kinds of identifiers were compared with each other. The fix was simple: don't do that 😅 That ensured that the constructor was only called once.

However, there was another more subtle issue that triggered the assert. Usually redefining the same component twice does not cause an assert, as the second registration should just verify whether it matches the first.

In this case, that 2nd registration check failed. The reason for this was that when ModuleA was defined, it registered the type as `namespace_a::ModuleA::TagA` with Flecs. However, the actual C++ typename is `namespace_a::TagA`. When the second registration compared the typename with the registered name in Flecs, it found a mismatch and asserted.

I only just realized that the simple_module C++ example doesn't do this either. While this code is not invalid (after the fix the code in the issue description will work) a cleaner way is to define the types inside the module struct, like:

```cpp
namespace namespace_a {
  struct module_a {
    struct TagA { };

    module_a(flecs::world& world) {
      world.module<module_a>();
      world.component<TagA>();
    }

  }
};
```

This ensures that the C++ typename equals the fully qualified name that is registered with Flecs. This gives you a bit of additional flexibility, as you can now for example in your application code obtain the component identifier like this:

```cpp

int main() {
  flecs::world world;

  world.import<namespace_a::module_a>();

  auto c = world.component<namespace_a::module_a::TagA>();

  std::cout << c.path() << std::end;
}
```

I'll close the issue, feel free to reopen if you are still experiencing issues!
