### ISSUE TITLE
No sync point between two systems with [inout] component query

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#354]
**Describe the bug**
Two systems both inout querying a component do not have a merge between them

**To Reproduce**
```c
struct Comp{};
ECS.system("Producer system", "[inout] Comp").iter([](iter &Iter) {
});
ECS.system("Dummy system", "[inout] Comp").iter([](iter &Iter) {
});
```

**Expected behavior**
A merge is inserted between the systems
![image](https://user-images.githubusercontent.com/9267866/111914985-494d0580-8a85-11eb-8425-e79801883045.png)

**Additional context**
Might be related to #327

**Comment by SanderMertens** [comment]
Ah, this does not insert a sync point, because (for as far as flecs knows) there is nothing to merge. Both components are directly subscribed for, which means that Flecs expects them to read/write the value inline (so accessing the component array directly, not using ecs_get or ecs_set).

To insert a sync point, you need to add an annotation to let flecs know that the system is writing to the stage, like:
```c
[out] :Comp
```
The `:` is the source operator, which here indicates that the component is not requested from any entity, but that the system is expected to write it. If a subsequent system then reads the component (either with `[in]` or `[inout]` a merge will be inserted.

This section of the manual has more details: https://github.com/SanderMertens/flecs/blob/master/docs/Manual.md#staging
