### ISSUE TITLE
template class cannot be used in system signature

### ISSUE THREAD

**Issue by chengts95** [SanderMertens/flecs#373]
**Describe the bug**
When using a template class, the system cannot run and throw runtime errors.
```bash
(null):25: error: expected end of expression or next element
    [in] ANY:Float<2>
                        ^
```
**To Reproduce**
```c++
template<int N>
struct Float{
     float values[N];
};
auto sys = world.system<const Float<2> >().each(
    [](flecs::entity , const Float<2> &n) {
...
    });
```
**Expected behavior**
This template class should be correctly handled by systems.

**Comment by SanderMertens** [comment]
I just checked in a fix for this, so that string-based expressions accept template types.

One additional thing to note is that in the latest version of the API the above code no longer creates a query string (it goes straight to the internal representation without converting the template args to a string), so there are two reasons why you'll no longer run into this problem :)

**Comment by chengts95** [comment]
Thank you very much!
