### ISSUE TITLE
Add get_mut member function to flecs::ref 

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#387]
**Describe the problem you are trying to solve.**
Saving a pointer to other entity's component to be modified from a system (related to Input processing, saved entity being Player and component being Input).

**Describe the solution you'd like**
Method get_mut allowing for modifications in the target component (returning non-const pointer).

**Comment by SanderMertens** [comment]
The reason `flecs::ref` does not have a `get_mut` is because it contains a cached pointer to an existing component. This cached pointer points to the actual underlying storage, and in multithreaded applications it would not be safe to modify this pointer directly. The only way to do this safely would be to add locking to the `ref` object, but that would increase its footprint by a lot.

The more straightforward approach is to just call `get_mut` on the entity for that specific component.

**Comment by Hexlord** [comment]
@SanderMertens I see, how about `flecs::ref::get_mut` doing just that? Executing `get_mut` on the entity?

**Comment by Hexlord** [comment]
Turned out to not be used heavily, so real priority, closing for now.
