### ISSUE TITLE
C++ Tag components (empty structs) not matched via term

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#402]
**Describe the bug**
Given struct `struct CAlignToNativeSize{};`
Have a query
```c
LayoutQuery = ECS.query_builder<>()
                      .term<const CAlignToNativeSize>()
                      .oper(flecs::Optional);
```
When iterating the query the term is never set, yet the tag is successfully retrieved using `.has`:
```c
for (auto Index : Iter) {
   
            if(AlignToNativeSizes.is_set()) {
                Debugf("This never happens");
            }
    
            if(Iter.entity(Index).has<CAlignToNativeSize>()) {
                Debugf("This happens");
            }
```

**Comment by SanderMertens** [comment]
For reference, this is what the full code would look like:
```c
struct CAlignToNativeSize { };

auto q = LayoutQuery = ECS.query_builder<>()
  .term<const CAlignToNativeSize>()
  .oper(flecs::Optional)
  .build();

q.iter([](flecs::iter& it) {
  auto AlignToNativeSizes = it.term<const CAlignToNativeSize>(1);

  for (auto Index : Iter) {
    if (AlignToNativeSizes.is_set()) {
    }
  }
}
```

What `is_set` does is check whether term contains a array pointer that is not `nullptr`, which in the case of an empty type is never the case. What actually should be prevented here is accessing an empty type as an iterable term. I'll add a static assert so that this:

```c
it.term<const CAlignToNativeSize>(1);
```

fails when `CAlignToNativeSize` is an empty type.

I've checked in some code so that to test whether an optional tag is set, you can do this:

```c
q.iter([](flecs::iter& it) {
  if (it.term_id(1) == it.world().id<CAlignToNativeSize>()) { }
}
```

**Comment by Hexlord** [comment]
> I've checked in some code so that to test whether an optional tag is set, you can do this:

Thanks, that helps!

**Comment by Hexlord** [comment]
@SanderMertens sadly `Iter.term_id(4) == Iter.world().id<CAnchorToNativeSize>()` is true, but `Iter.entity(Index).has<CAnchorToNativeSize>()` is false, so new method not working correctly, will resort to `entity::has` for now
