### ISSUE TITLE
WIP: Handles Over Pointers

### ISSUE THREAD

**Issue by ArnCarveris** [SanderMertens/flecs#43]
This will allow not mess with `C++` type system, need to replace all necessary `typedef` via `struct`. 

See. https://floooh.github.io/2018/06/17/handles-vs-pointers.html

**Comment by SanderMertens** [comment]
@ArnCarveris can you detail which types you would like to see turned into a handle and why?

We discussed `ecs_entity_t` and `ecs_type_t`, but for now decided that they will remain plain typedefs for the following reasons:
- `ecs_entity_t` can be used in bitwise OR expressions to apply type flags which becomes inconvenient/inconsistent when put in a struct (should the typeflags enum also become a struct?)
- `ecs_type_t` remains a vector so that it is clear that a type can be used as a vector, and there is no need to duplicate (parts of) the vector API for types.

**Comment by SanderMertens** [comment]
Closing this issue as it is too broad.
