### ISSUE TITLE
Rule-of-three for flecs::vector and flecs::map

### ISSUE THREAD

**Issue by codylico** [SanderMertens/flecs#468]
**Describe the problem you are trying to solve.**
The `flecs::vector` and `flecs::map` C++ wrappers currently do not have destructors, so memory leaks could occur when a wrapper goes out of scope. In addition, neither wrapper has a copy assignment operator (i.e. `operator=`), so any default assignment may do the wrong thing (for example, copy the pointer to the underlying `ecs_vector_t`).

**Describe the solution you'd like**
I would like both `flecs::vector` and `flecs::map` to implement `~vector()` and `operator=(const vector&)` (`~map()` and `operator=(const map&)` respectively). At a minimum,
- the destructor should call `ecs_vector_free`/`ecs_map_free` on the private pointer
- the copy assignment operator, if not given an implementation, should be deleted (`operator=(const vector&) = delete;`)

There may also need to be a copy constructor (`vector(const vector&)`) that is handled similarly to the copy assignment operator. Also, since flecs seems to target C++ 2011 (or later), move constructors and move assignment operators could be useful (to just move the pointer instead of a deep copy).

**Caveat**
Since the vector wrapper can be constructed to use either an outside `ecs_vector_t` or an internal `ecs_vector_t`, I'm not sure what the correct lifetime for the wrapped `ecs_vector_t` should be. As the code on `master` branch is, the user can't free an internal `ecs_vector_t`.

The map wrapper does not seem to have a similar problem.

**Comment by SanderMertens** [comment]
>  I'm not sure what the correct lifetime for the wrapped ecs_vector_t should be

This is the key challenge. The main purpose of flecs::vector is to wrap around internal vectors (such as an entity type and is used in code like this, where bad things would happen if flecs::vector would destruct:

```c
std::cout << e.type().str() << std::endl; // type() returns a flecs::vector wrapped around the entity's type
```

What perhaps adds to the confusion is that the class contains constructors that can allocate, but this is just done to allow for convenient initialization of vectors, such as in code like this:

```c
flecs::vector<Position> pos = {
    {10.0f, 20.0f},
    {30.0f, 40.0f},
    {50.0f, 60.0f}
}
```

You are correct that this code leaks, and that the current class doesn't provide a mechanism for cleanup. The reason this hasn't been an issue is because the vector class has been used in C++ versions of C types to provide a binary compatible yet much more convenient to use interface. In such code the cleanup would typically happen by a (component) destructor written in C. An example:

```c
#ifndef __cplusplus
struct Foo {
  ecs_vector_t *ints;
};
#else
struct Foo {
  flecs::vector<int> ints;
};
#endif

ECS_DTOR(Foo, ptr, {
  ecs_vector_free(ptr->ints);
});
```

Adding a destructor to `flecs::vector` would make this more difficult to do since it would turn `Foo` into a non-trivial type that now suddenly needs to care about move semantics etc. Also, prevent freeing a vector that is not managed by the `flecs::vector` object would require adding at least one more field to the class, which means it would no longer be binary compatible.

All of that is a long-winded way of saying that the flecs::vector and flecs::map types are not (and should not be used as) general purpose data structures. If you need a vector in C++, you should definitely prefer using std::vector. Note that for anything other than POD types, the current implementation will also leak or crash, as it makes no attempt to correctly invoke copy/move functions of the contained type.

I'll add a `destruct` method to both classes to address the most glaring issue (not being able to free resources). I have no plans though to turn these classes into general purpose containers.

**Comment by codylico** [comment]
> The main purpose of flecs::vector is to wrap around internal vectors (such as an entity type) and is used in code like this, where bad things would happen if flecs::vector would destruct:
> ```
> std::cout << e.type().str() << std::endl; // type() returns a flecs::vector wrapped around the entity's type
> ```

Something tells me that the destructor would be delayed long enough in this example (see [temporary object lifetime on cppreference.com](https://en.cppreference.com/w/cpp/language/lifetime#Temporary_object_lifetime)), but I could be wrong, and it is not important for this discussion.

> You are correct that this code leaks, and that the current class doesn't provide a mechanism for cleanup. The reason this hasn't been an issue is because the vector class has been used in C++ versions of C types to provide a binary compatible yet much more convenient to use interface. In such code the cleanup would typically happen by a (component) destructor written in C.

Ah. Now I see.

> All of that is a long-winded way of saying that the flecs::vector and flecs::map types are not (and should not be used as) general purpose data structures. If you need a vector in C++, you should definitely prefer using std::vector. Note that for anything other than POD types, the current implementation will also leak or crash, as it makes no attempt to correctly invoke copy/move functions of the contained type.

That much I could tell from the source. (As a side note, I wonder if there should be a `static_assert(std::is_trivially_copyable<T>::value, "...")` or something in the `flecs::vector`.)

> I'll add a destruct method to both classes to address the most glaring issue (not being able to free resources). I have no plans though to turn these classes into general purpose containers.

Sounds good to me.
