### ISSUE TITLE
Way to get rows from another table

### ISSUE THREAD

**Issue by ThomasBrixLarsen** [SanderMertens/flecs#64]
I find I need something like `ecs_rows_t *ecs_get_rows(ecs_world_t *world, ecs_type_t system)`, to update a different table, based on table associated with the calling system.

IOW system table used to update another system table.

My current workaround is to use `ecs_run` to find `ecs_entity_t` and `ecs_get_ptr` for each component. But the manual explicitly says to limit use of `ecs_get*`.

**Comment by SanderMertens** [comment]
Hi @ThomasBrixLarsen, could you provide more details around what you are trying to accomplish? For example, how do you know which of the matched tables you need?

**Comment by ThomasBrixLarsen** [comment]
Let's say I want to update a table based on an external source.

I have these entities:
Area - Id:int, name:string, Cars:int, Orders:int
AreaUpdate - Id:int, Cars:int, Orders:int, Update:tag

A lot of AreaUpdates are inserted from an external source.

Goal: A system merges AreaUpdates into Area where Id=Id. Any areas that are not updated must have Cars and Orders set to 0.

I could match on "Id, Cars, Orders, ?Update" and use EcsOnAdd. But I would prefer to have the processing happen later using EcsOnUpdate. If I match on "Id, Cars, Orders, ?Update" the system will needlessly be called every frame.

Instead I would like to match "Id, Cars, Orders, Update" using EcsOnUpdate, and call something like `ecs_get_rows` with "Id, Cars, Orders, !Update" to get the table I want to mutate.

**Comment by SanderMertens** [comment]
@ThomasBrixLarsen makes sense. Currently the only way to do this in ECS is to create an `EcsManual` system that matches `Id, Cars, Orders, !Update`, and use `ecs_run` to find the right entity.

Alternatively (this may not be possible, I'm just thinking out loud), you could consider to use the `Id` as the entity directly, since `ecs_entity_t` is an integer as well. That way you can use the lookup mechanism of Flecs to lookup entities, instead of having to iterate manually.

Of course, you could also create an external data structure (not stored in ECS) that maps an `Id` to an `ecs_entity_t`, and when you walk over the updates, you lookup the actual entity and update it. You would have to use `ecs_get` or `ecs_set`, but that is likely still more efficient than having to iterate over all the `Area` entities.

**Comment by SanderMertens** [comment]
@ThomasBrixLarsen I'm closing this question, feel free to reopen it if you would like to discuss further.
