### ISSUE TITLE
Component registration fails across boundaries when using a custom name

### ISSUE THREAD

**Issue by Manningham** [SanderMertens/flecs#685]
**Describe the bug**
Component field reflection registration through the `member` C++ API fails when performed in a separate DLL from the one in which the `flecs::world` is initialized. `flecs_name_index_ensure` aborts:

e.g.1 using `.member(flecs::F32, "MemberName")` overload:
"conflicting id registered with name 'EcsMember' (ALREADY_DEFINED)"

e.g.2 using `.member<float>("MemberName")` overload:
"conflicting id registered with name 'f32' (ALREADY_DEFINED)"

It's suspected that this happens because the reflection-related components do not have their static IDs registered yet in these other DLLs when they are used there for the first time ([discord discussion](https://discord.com/channels/633826290415435777/731400638637932604/955734696812240926)). This seems to be confirmed by the workaround of declaring a `flecs::world()` in each DLL to force the initialization of these static IDs before use, which seems to work.

This was observed in an Unreal Engine 5 project where the flecs world is created in one UE module and a component is registered with reflection data in another UE component - UE modules are often built as separate DLLs ([discord discussion](https://discord.com/channels/633826290415435777/731400638637932604/950863663328268369)).

**To Reproduce**
*Suspected* Steps to reproduce the behavior - I haven't actually done all this since it's pretty labor intensive for a C++ noob like me:
1. Create a C++ project which depends on some other code in a DLL
2. Ensure that the flecs world is instantiated in the main project
3. Expose a function from the DLL code to the main project which accepts the flecs world by ref/ptr and registers a component with reflection bindings using the `member` API
4. Invoke the function from the main project
5. Running this code should generate the error

**Expected behavior**

It would be nice if flecs could detect this situation and ensure its reflection component IDs are set before use across DLL boundaries. 

**Additional context**
Add any other context about the problem here (operating system, hardware, ...).

Windows, Unreal Engine 5.0EA

**Comment by nneesshh** [comment]
static variable can't cross dll，use global variable instead

**Comment by Manningham** [comment]
> static variable can't cross dll，use global variable instead

The statics in question are defined in flecs, not the client app. Agree it would be better to not use them, but don't know how viable it is to move away from them (haven't looked).

**Comment by SanderMertens** [comment]
@nneesshh @Manningham Static variables are the fastest way to find a component id for a given type, which is necessary for any operation that looks like this:
```c
e.add<Foo>(); // finds component id for Foo in static variable
```

The alternative to this would have to rely on a lookup, which would make the C++ API slower than it could be / slower than C.

The issue is not actually the usage of static variables (flecs will initialize those across boundaries) but with components that are registered using a custom name, for example:

```c
world.component<Foo>("MyNameInsteadOfFoo");
```

When a component is re-registered implicitly across a boundary that custom name is not provided, and a name mismatch error is thrown. This shows up for some of the components registered by Flecs addons, as they are registered with a custom name.

**Comment by SanderMertens** [comment]
Fixed!
