### ISSUE TITLE
Why is <stdint.h> only included when __BAKE__ isn't defined?

### ISSUE THREAD

**Issue by anabh4569** [SanderMertens/flecs#69]
I was trying to do "bake clone https://github.com/SanderMertens/flecs" on WSL, and was hit with a bunch of "unknown type name 'uint64_t/uint32_t/uintptr_t/etc'". Is there something additional with the setup for WSL that I missed?

**Comment by SanderMertens** [comment]
When flecs is built with bake it gets `stdint.h` from `bake.util`. Since Windows does not come out of the box with a `stdint.h`, `bake.util` has its own which is included at `bake_util.h:66`

```c
#if defined(_WIN32)
...
#include "bake-util/win/stdint.h"
#else
...
```

I haven't tried compiling for WSL yet, but my guess is that the defined macro's are different, which causes `stdint.h` to not be included anywhere. I don't have WSL setup here and am unsure whether it has its own `stdint.h`. If you however find a solution, let me know and I'll fix it!

**Comment by WEREMSOFT** [comment]
@anabh4569 Can we have more information regarding this issue? Which linux distro are you using in SSL?

**Comment by anabh4569** [comment]
Ubuntu.

**Comment by WEREMSOFT** [comment]
@anabh4569 

Ok, I think that you don't have your C environment properly installed on your WSL. Please try the following:

sudo apt-get update && sudo apt-get dist-upgrade
sudo apt-get install build-essential gdb

After that, follow the build steps on the build section of the Flecs page(the one that installs bake)

Please let me know if this works.

Thanks

**Comment by SanderMertens** [comment]
Closing this issue, as I think this has been addressed. If you are still seeing issues, feel free to reopen.
