### ISSUE TITLE
Rollbacks for deterministic sim

### ISSUE THREAD

**Issue by RomanZhu** [SanderMertens/flecs#7]
Hey!
Awesome project

I'm interested in how you would approach making rolling back a few (10 Max) frames for changing inputs and resimulation

I'm not that familiar with C. 
What I was thinking is if we could allocate ten times as much memory as usually used and at the end of each frame copy all memory related to world to free/oldest block

When it's time to rollback - we clear memory of current frame and copying from storage block. (Or we could start using that storage block as current world)

Another way is store inverted changes then if 
-entity was deleted then we store command to create entity with all components
-component changed then we store command to set component value to old value
-etc

Thanks :D

**Comment by SanderMertens** [comment]
I think a combination of these two approaches would be interesting. First of all, we would need to buffer some data of the frames, because most of the data in systems is updated in place (no API call we could track). That is obviously costly, but there are a few possible optimizations:

- Annotate systems with read/write, so flecs knows which components will be written and which will be read. That way we could make a system write to the next frame, vs. writing to the current frame and then to a massive memcpy. Basically systems would read from the current frame, and write to the next frame.

- Mark components as "static". Some data may not change during frames, like static buildings, and these would not have to be copied between frames.

With these optimizations, we would only need to copy components that are read+write. Additionally, we could not copy components that aren't written by systems at all. For those components, we could take the command approach, where we store a list of commands per frame.

As long as the application "behaves" (like, don't store a pointer to a component that is used across frames - which would be dangerous anyway) I think this approach could work, but curious to hear your thoughts!

**Comment by RomanZhu** [comment]
Yep, filtering of non changed data could save a lot of performance
Do you think it's possible to generalize that stuff to work with any components?

**Comment by SanderMertens** [comment]
I think so. By default flecs could just copy all data between frames. Then if applications add things like read/write annotations and mark components/types as const, things just become more efficient.

This is what I mean with read/write annotations:
```c
ECS_SYSTEM(world, MySystem, EcsOnFrame, in Foo, out Bar);
```

**Comment by RomanZhu** [comment]
What if system reads and writes to same component? That behaviour could be the default
I think mesh data and colliders won't be changed, once they entity is spawned from prefab then nobody will write to those components, so they will be filtered out by annotations

Do you think that behavior is worth adding into flecs? I'd imagine it will require a lot of rewriting .-.

**Comment by SanderMertens** [comment]
Yes, read/write components would be the default.

I think it is worth adding. I'm working on a simulation use case myself as well, and this issue has come up. The simple case is not too hard to implement (copy all data). Read/write + const components would take a bit more work, but I don't think I would need to rewrite a lot of code.

Every "archetype" (entity type) is stored internally as a collection of arrays, one for each component.  This feature would basically only need to copy the arrays of the non-const components, and copy only the pointer of the array for const components.

This is the data structure where the copy would happen: https://github.com/SanderMertens/flecs/blob/master/include/private/types.h#L164

**Comment by RomanZhu** [comment]
Oh, sounds awesome!
The way I imagine API is
1)Calling Execute on part of the systems (you don't need to rerender while doing fast-forward after rewind), At the end of each Execute that "delta" is stored, frame number is increased.
2)Calling Rewind with number of frames to go back - after that world will end up in old state and frame number will be reduced.

**Comment by nxrighthere** [comment]
Yea, it would be great to have this possibilities. Looking forward to it. 👍
