### ISSUE TITLE
Missing definition for `ecs_meta_move`

### ISSUE THREAD

**Issue by sro5h** [SanderMertens/flecs#723]
**Describe the bug**
The definition of the function `ecs_meta_move` seems to be missing from `flecs.c` and `meta.c`. Thus usage of the function results in a linker error.

**Expected behavior**
No linker error.

**Additional context**
Should not really matter, but i am running Fedora 35 with gcc 11.3.1

**Comment by SanderMertens** [comment]
Fixed! 

I made a few changes:

- renamed the function to `ecs_meta_elem`
- it can only be used with collections

Rationale: implementing an `ecs_meta_move` for structs could not be made more efficient (at least not without introducing additional data structures) than calling `ecs_meta_next` multiple times. This is because of nested structs, and the list of operations being "flattened": you can't easily jump over 3 members without knowing how many members those members have. Instead, the `ecs_meta_member` function provides an O(1) way to jump around a struct.

`ecs_meta_move` (now `ecs_meta_elem`) does make sense for collections, where "jump to the nth element" is a simple O(1) operation where the cursor just sets the index to the current element.
