### ISSUE TITLE
world isolation

### ISSUE THREAD

**Issue by bbdb68** [SanderMertens/flecs#735]
**Describe the bug**
when instancing worlds in different parts of the code, is seems they are not independant (eg when building Catch test cases)
in the example below, run_test2 fails when importing modules. If the call to run_test1 is commented, then run_test2 runs smoothly.

**To Reproduce**

```
struct ModuleA
{
  ModuleA(flecs::world& world)
  {
    world.module<ModuleA>();
  }
};

struct ModuleB
{
  ModuleB(flecs::world& world)
  {
    world.module<ModuleB>();
  }
};

run_test1(void)
{
  flecs::world world;
  world.import<ModuleA>();
}

run_test2(void)
{
  flecs::world world;
  world.import<ModuleB>();
  world.import<ModuleA>();
}

int main(void)
{
   run_test1();
   run_test2();
   return 0;
}
```

**Expected behavior**
each run function should be able to execute

**Additional context**
discovered using catch on windows

**Comment by SanderMertens** [comment]
This is expected behavior- though it may not be obvious at first why. The C++ API stores global static ids for components (which allows for fast almost free lookups), and as a result they are shared across worlds.

In this example, the first test assigns an id to `ModuleA`, which in the second test is assigned to `ModuleB`. When the second test then registers `ModuleA`, the id it was registered with is already in use by `ModuleB` and you get an assert.

There is a function to make it work, calling `flecs::reset()` in between tests will fix the problem, as it will cause the code to discard all old ids when registering a component.

**Comment by SanderMertens** [comment]
> an id is globally created for the module type

The id is created by the world and then shared with other worlds. In the second test you start with a fresh world that doesn't know that `ModuleA` exists, and so it will assign the id that in the first test was assigned to `ModuleA` to `ModuleB`.

**Comment by SanderMertens** [comment]
Closing the issue for now, feel free to reopen it if you have more questions!
