### ISSUE TITLE
Copy all world data for every frame

### ISSUE THREAD

**Issue by MohammadMDSA** [SanderMertens/flecs#743]
Hi! I am developing my first mutli-threaded game engine. As far as I understand, I have to update and render the world simultaneously. The idea is to update frame N while renderer is rendering based on game data from frame N-1. So I need a very high performance copy function to deep copy my entire world, every frame after updating my frame so I can give to renderer as the next frame game data reference.
Is there any function or technique with flecs that can help me achieve my goal?
Any help, idea, resource, project reference, and anything is appreciated!

**Comment by SanderMertens** [comment]
There are two things you could do that are pretty fast. The first one is to create a query that matches all the entities you need in the renderer. The second one is to use the snapshot API:
https://github.com/SanderMertens/flecs/blob/master/include/flecs/addons/snapshot.h

Creating a snapshot is the easiest option, but could be doing more than you need. It would copy all components for all entities, which would also include things like entity names that you probably don't need while rendering. Another potential downside is that a snapshot data is organized as ECS tables, which may not be the most optimal data structure for your renderer.

Using a query takes a bit more work since you have to do the copying yourself, but is still pretty fast since queries give you access to entire component arrays. You also have more flexibility when it comes to which components to skip, or how to store the data in a format that's convenient for the renderer. Queries maintain a cache of matched tables, so query iteration itself has very low overhead.

Let me know if that helps!

**Comment by MohammadMDSA** [comment]
Thank you for your answer.I have a question: When I query for a component and start to iterate over result, doesn't the iter function return a reference to the original component? If so, it doesn't work for me.I actually haven't understood what "cached result" mean in queries. If it means the result data is a copy of the original data, it would be awesome!
-------- Original message --------From: Sander Mertens ***@***.***> Date: 6/16/22  11:01 PM  (GMT+03:30) To: SanderMertens/flecs ***@***.***> Cc: Mohammad Sami ***@***.***>, Author ***@***.***> Subject: Re: [SanderMertens/flecs] Copy all world data for every frame (Issue #743) 
There are two things you could do that are pretty fast. The first one is to create a query that matches all the entities you need in the renderer. The second one is to use the snapshot API:
https://github.com/SanderMertens/flecs/blob/master/include/flecs/addons/snapshot.h
Creating a snapshot is the easiest option, but could be doing more than you need. It would copy all components for all entities, which would also include things like entity names that you probably don't need while rendering. Another potential downside is that a snapshot data is organized as ECS tables, which may not be the most optimal data structure for your renderer.
Using a query takes a bit more work since you have to do the copying yourself, but is still pretty fast since queries give you access to entire component arrays. You also have more flexibility when it comes to which components to skip, or how to store the data in a format that's convenient for the renderer. Queries maintain a cache of matched tables, so query iteration itself has very low overhead.
Let me know if that helps!

**Comment by SanderMertens** [comment]
Yes, queries return a reference to the actual component, so you can update them inline. Making a copy of the components by default would be much more expensive.

However, you can defer an update for a component! Take this example:
```c
world.system<Position>()
  .each([](flecs::entity e, Position& p) {
    e.set<Position>({10, 20}); // this will be processed at the end of the frame
  });
```

This example has more information: https://github.com/SanderMertens/flecs/tree/master/examples/cpp/systems/sync_point

**Comment by SanderMertens** [comment]
Closing the issue for now, feel free to reopen if you have follow up questions!
