### ISSUE TITLE
Non C string API?

### ISSUE THREAD

**Issue by tomc1998** [SanderMertens/flecs#77]
The great thing about this library is that it's written in C, meaning it can be wrapped by pretty much any other language. This is great! However, most of the APIs accept NUL-terminated strings. A lot of languages are using pointers + lengths to describe strings (see rust's string slices, for example).

Is it possible to add a lower-level API which takes a char* and a string length, then have the C api call into that with the pointer + strlen?

In ecs_parse_component_expr() (in parser.c) the first think you do is take the strlen of the expression anyway. I guess stuff not being nul-terminated would mean you couldn't use strcmp (?)

**Comment by SanderMertens** [comment]
What makes this challenging is that the C library expects 0 terminated strings. Some functions have alternatives to which you specify a length (like strncmp). Others don't (like printf).

For the parsed strings, like system signatures or type expressions I could consider supporting length-annotated strings since they are only used internally anyway after parsing, and, like you said, I do a strlen anyway.

However, entity ids cannot be changed easily to length annotated strings (the ones stored in `EcsId` and `ecs_lookup`). These strings are not encapsulated, meaning that the application can directly get/set them:

```c
ecs_set(world, e, EcsId, {"Hello World"});
```

In this case, the `ecs_set` function has no idea about the type of the component, so it can't do any "magic" to derive the string length.

What I could consider, is adding a `EcsIdN` (or something) component that accepts length-annotated strings, so you could do:

```c
ecs_set(world, EcsIdN, {my_string, 10});
```

And then have Flecs evaluate EcsIdN as well when doing a lookup. There should then also be a lookupn: `ecs_lookup(world, my_string, 10)`;

It would be a pretty big effort, but for as far as I can see it's possible.

**Comment by tomc1998** [comment]
Hmmmm, no I think maintaining a good C interface whilst also having non nul-terminated strings would be too much complexity, didn't think about the ecs_set cases...

Maybe once the framework's a bit older I'll come back to this, wouldn't want to hamper any useful changes with annoying 'this isn't nul terminated!' gotchas.

**Comment by SanderMertens** [comment]
@tomc1998 I agree. Perhaps once the APIs are more stable, a more thorough approach could be taken where Flecs supports multiple string types. Strings have also been an issue with C#, where due to how it manages memory pointers to strings can become invalid, so it's definitely something that should be addressed at some point.

I'll close this issue for now, but will keep this in the back of my head for when the API is mature enough for a change like this.

**Comment by raizam** [comment]
just my two cents, what I did to handle C strings is, on allocation, to write the size on the first four bytes, and then write the string.
This way it doesn't introduce a type, and when a function request a size, I just look for the size behind.

**Comment by dumblob** [comment]
It seems the API has nicely evolved "two times" (v1 -> v2 and nowadays v2 -> v3) since this discussion took place.

Do you think this string question might get more interesting with the newest API?
