### ISSUE TITLE
add / set order on observer

### ISSUE THREAD

**Issue by bbdb68** [SanderMertens/flecs#775]
When you create an observer with both a tag and a component, onSet may be called before onAdd

example (with 3.02 beta), 

```
TEST_CASE("set_before_add")
{
  flecs::reset();
  struct Double { double value; };
  struct Scale {};

  flecs::world world;
  bool onSet_is_called = false;
  bool onAdd_is_called = false;

  world.observer<Scale, Double>()
    .event(flecs::OnAdd)
    .each([&onAdd_is_called](flecs::entity e, const Scale& scale, Double& d)
      {
       d.value = -1;
       onAdd_is_called = true;
      });

  world.observer<Scale, Double>()
    .event(flecs::OnSet)
    .each([&onSet_is_called](flecs::entity e, const Scale& scale, Double& d)
      {
        d.value = +1;
        onSet_is_called = true;
      });

  auto e = world.entity();
  e.set<Double>({ 4 });
  e.add<Scale>();

  CHECK(onSet_is_called);
  CHECK(onAdd_is_called);
  CHECK(e.get<Double>()->value == +1);
}

```

in that case, onSet is called before onAdd and the test fails. But if you do
```
  e.add<Scale>();
  e.set<Double>({ 4 });
````
onAdd is called before onSet

**Comment by SanderMertens** [comment]
This is expected behavior. In this case the first event that causes both observers to match is `add<Scale>`. When more than one observer matches the same event, the order in which observers are ran is undefined.

When you flip the statements, the `set` first causes an `OnAdd` event (when the component is added), followed up by an `OnSet` event, when the component is set. That's why in this case the `OnAdd` observer will always be triggered first.

The reason why the `OnSet` observer is invoked for the `add` event is that the observer contains the `Scale` tag, which is an empty type and can therefore never be set. Because of this `OnSet` observers for tags actually use the `OnAdd` event. Without this, an `OnSet` observer would never be able to match both components and tags.

Under the hood observers for multiple components are split up into single-component observers which register themselves for an event. Because both `OnAdd` and `OnSet` observers register themselves in the same `OnAdd` list for the `Scale` tag, the order in which they are invoked is undefined.

Hope this helps, feel free to reopen the issue if you have more questions!

**Comment by bbdb68** [comment]
Sander, thanks for your response.

My remark came from older documention I believe, where the descripton of onAdd and onSet (but probably for triggers) made me tought that `OnAdd` was to be called before (instantiation has to happen first...). I still find this behaviour a bit surprising, I wonder what would be the cost and/or side effect to sort the observer list so that `OnAdd` is run first ? (a bit like  pipeline stages ?)  As en example, the `OnAdd` list could retain the original event of the observer and use it for sorting ?

And if it is a bad idea to change this behaviour, I suggest to document it, as for systems ordering

**Comment by SanderMertens** [comment]
> My remark came from older documention I believe, where the descripton of onAdd and onSet (but probably for triggers) made me tought that OnAdd was to be called before

You are probably referring to this diagram: https://github.com/SanderMertens/flecs/blob/master/docs/Manual.md#component-add-flow

What this shows is that `OnAdd` _events_ are emitted before `OnSet` events. This naturally causes `OnAdd` observers to get triggered before `OnSet` observers, but only if those two events are emitted as the result of a single operation (such as, a component that is added as the result of a `set`).

The reason why in the example code the `OnAdd` observer is not always triggered before the `OnSet` observer is because the event that causes the `OnSet` observer to match is not actually an `OnSet` event:

```c
  e.set<Double>({ 4 }); // no observers are triggered
  e.add<Scale>(); // triggers both observers with an OnAdd event
```

When two observers get triggered by the same event the order in which they are invoked is undefined.

> I wonder what would be the cost and/or side effect to sort the observer list so that OnAdd is run first

This is not possible in the current architecture because of two reasons:
- observers are stored in unordered maps
- observers for N components are split up in N observers for a single component. The observer for `Scaled` is added to the administration for the `OnAdd` event. That administration doesn't keep track of event id, because all observers in its list are by definition `OnAdd` observers.
