### ISSUE TITLE
flecs::is_callable does not work for types with multiple overloaded () operators

### ISSUE THREAD

**Issue by happyxianyu** [SanderMertens/flecs#785]
**Describe the bug**
If there exsits more than one overloaded operator() method, entity.set<Component>() leads to compiler error C3556 in msvc. According to https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3556?view=msvc-170, this is because the compiler cannot deduce the type of operator().

**To Reproduce**
Example code:
```
void foo() {
    struct Foo {
        int x;

        // compiler error when there exists several overloaded operator()
        void operator()(int) {}
        void operator()(float) {}
    };

    flecs::world w;
    auto e = w.entity();

    e.set<Foo>(Foo{});
    // or
    auto v = flecs::is_callable<Foo>::value;
    // lead to error C3556 in msvc
}
```

**Expected behavior**
e.set<Foo> should work.

**Additional context**
flecs 3.0.2
Visual studio 2022

**Bug fix suggestion**
We can use std::is_invocable to substitue is_callable. I tried std::is_invocable and it works well for this case.

**Comment by SanderMertens** [comment]
The function traits code that implements `is_callable` is from this stack overflow answer: https://stackoverflow.com/questions/27024238/c-template-mechanism-to-get-the-number-of-function-arguments-which-would-work

This part is causing the trouble on msvc:
```cpp
template <typename T>
struct function_traits_no_cv<T, decltype((void)&T::operator())>
    : function_traits_impl<decltype(&T::operator())> {};
```

I'm not sure if this can be rewritten in a way that fixes the problem with multiple overloads of the `()` operator. The code is also used to determine arity and argument types of a callable type, which obviously don't make sense if a type has multiple callable signatures.

I can't use `std::is_invocable` because the API needs to be C++11 compatible. Adding a check on whether the code is compiled with C++17 is also not straightforward as all compilers require different ways to test for this. 

I did some research on alternative ways to implement `is_callable` in C++11 but didn't find anything that works for as many cases as the current implementation does (each approach just seems to have different limitations).

Maybe there is a way to solve this in C++11 but my template-jitsu is not up to par. I'll close this issue for now as I'm not sure it can be fixed, but will keep an eye out for possible solutions.

**Comment by ai623** [comment]
We do not need to detect c++ version automatically. We can just use ifdef directive so that user can choose whether enable c++ 17 feature or not.

For example,
#ifdef ENABLE_CPP_17
template<...>
using is_callable = std::is_invocable<...>
#else
...

#endif

**Comment by happyxianyu** [comment]
> I can't use `std::is_invocable` because the API needs to be C++11 compatible. Adding a check on whether the code is compiled with C++17 is also not straightforward as all compilers require different ways to test for this.

Maybe we don't need to detect C++ version automatically. We can just use #ifdef directive so that the user can choose whether to enable C++17 feature or not.

For example,
```
#ifdef ENABLE_CPP_17
template<...>
using is_callable=std::is_invocable<...>;

#else 
...
#endef
```
