### ISSUE TITLE
When enabling threading, all threads are created and destroyed per pipeline used

### ISSUE THREAD

**Issue by Tisten** [SanderMertens/flecs#957]
**Describe the bug**
In my application I have a few pipelines, one to update systems before physics, another pipeline after physics, and one which I would like to run to gather rendering data which interpolates between two simulation updates. So far I've only run these serially, but I tried setting thread count to 2 and suddenly flecs started spawning and killing several threads per frame, not reusing the spawned ones. This happens every time I switch pipeline which I do several times per frame. Spawning threads is expensive so this kills performance.

Based on this issue I kind of understand that the design of pipelines is meant to only have one, either the standard one or a custom one, and that the code which doesn't deal with flecs' data is supposed to be called from a flecs phase anyway. When reading the [phase and pipeline documentation](https://github.com/SanderMertens/flecs/blob/master/docs/DesignWithFlecs.md#phases-and-pipelines) this wasn't clear. I would appreciate if switching pipelines was performant, but if the desired design is to only have a single pipeline then that should at least be properly documented, both in text and the api docs of `ecs_set_pipeline()`

**Comment by SanderMertens** [comment]
The reason this happens is because the way worker threads are kept synchronized on the same worker is through sync points, which make a thread progress to the next segment of a pipeline.

A different pipeline has different sync points, which is why changing pipelines resets the administration. In a single threaded application this is a cheap operation, but you're right that in a multithreaded application it's not.

Pipeline switching is most typically used when switching game states (for example, when going from game mode to menu mode), which is infrequent. Can you provide a bit more context on why pipelines are switched multiple times per frame? That's a use case I indeed hand't considered yet.

In nay case, it should be possible to adapt the current code to make switching more efficient.

**Comment by Tisten** [comment]
> Can you provide a bit more context on why pipelines are switched multiple times per frame?

The way our pipelines got structured is that plugins register systems which will run in a pipeline and a phase, and they can define phases and their ordering themselves. These phases are intended to specify dependencies between systems, and not to say that only a specific system can run in a specific phase.
Like:
```
	ecs->DependsOn(PRE_UPDATE_PHASE, g_Physics->m_CreateActorsPhase);
	ecs->DependsOn(g_Physics->m_CreateActorsPhase, g_Physics->m_AttachShapesPhase);
	ecs->DependsOn(g_Physics->m_AttachShapesPhase, g_Physics->m_AddActorsPhase);
	ecs->DependsOn(g_Physics->m_AddActorsPhase, g_Physics->m_RemoveActorsPhase);
	ecs->DependsOn(g_Physics->m_RemoveActorsPhase, ON_UPDATE_PHASE);
```
The game simulation runs in a lower frequency than the rendering, and the simulation will generate data which is later used by the rendering to interpolate smoother changes. We want to do this interpolation in parallel with the next frame's simulation but still act on the same entities, so we would like to run several pipelines in parallel, and not sequencially.

This was the use case, but I think flecs works in a different way compared to our design so we will create our own pipeline instead. But I still wanted to point out that the cost of switching pipelines was surprisingly high, and that this at least should be documented.

Thanks for your great support of the library.

**Comment by SanderMertens** [comment]
Agreed, I added a note to the systems manual!
