### ISSUE TITLE
Filters doesn't exclude disabled objects

### ISSUE THREAD

**Issue by Tisten** [SanderMertens/flecs#973]
**Describe the bug**
After disabling a tag or component on an entity, a query for it will no longer return the entity. But filters will.

**To Reproduce**
I wrote a test for it. It is an adapted version of `EnabledComponents_query_disabled`:
```
void EnabledComponents_filter_disabled() {
    ecs_world_t *world = ecs_mini();

    ECS_COMPONENT(world, Position);

    ecs_entity_t e1 = ecs_new(world, Position);
    ecs_entity_t e2 = ecs_new(world, Position);
    ecs_entity_t e3 = ecs_new(world, Position);

    ecs_enable_component(world, e1, Position, true);
    ecs_enable_component(world, e2, Position, false);

    ecs_filter_t f = ECS_FILTER_INIT;
    test_assert(NULL != ecs_filter_init(world, &(ecs_filter_desc_t){
        .storage = &f,
        .expr = "Position"
    }));
    ecs_iter_t it = ecs_filter_iter(world, &f);

    int32_t table_count = 0, count = 0;

    while (ecs_filter_next(&it)) {
        int32_t i;
        for (i = 0; i < it.count; i ++) {
            test_assert(it.entities[i] != e2);
            test_assert(it.entities[i] == e1 || it.entities[i] == e3);
            test_assert(ecs_is_enabled_component(world, it.entities[i], Position));
        }
        count += it.count;
        table_count ++;
    }

    test_int(count, 2);
    test_int(table_count, 2);

    ecs_fini(world);
}
```

**Comment by SanderMertens** [comment]
Right, there are a few features that rely on specialized iteration inside of tables, which is currently only supported by queries:
- Disabled components
- Union relationships
- Flattened hierarchies

Adding support for these features are on the roadmap but may take some time to complete, as the plan is to integrate them with the rule engine, and eventually have the rule engine replace the filter implementation.

I'm marking this as enhancement since it's not expected to work.

**Comment by SanderMertens** [comment]
This has been fixed in v4, where filters, rules and queries have been merged into a single API.
